/**
 * ExportSheet — selective, doctor-friendly data export.
 *
 * Opens a bottom sheet where the user picks what to include, then generates
 * a clean HTML document in a new tab — ready to Print → Save as PDF.
 *
 * Sections available:
 *   injections (filterable by compound)
 *   lab results
 *   blood pressure
 *   body weight
 */

import { useMemo, useState } from 'react'
import { format, parseISO, subMonths } from 'date-fns'
import { FileText, X } from 'lucide-react'
import type { Compound, InjectionLog, LabExam, VitalLog } from '../lib/db'
import type { EnrichedResult } from '../lib/insights'

type DateRange = '1M' | '3M' | '6M' | '1Y' | 'ALL'

const RANGE_LABELS: Record<DateRange, string> = {
  '1M': 'Last month', '3M': 'Last 3 months',
  '6M': 'Last 6 months', '1Y': 'Last year', 'ALL': 'All time',
}

function cutoffFor(range: DateRange): Date | null {
  if (range === 'ALL') return null
  const n = { '1M': 1, '3M': 3, '6M': 6, '1Y': 12 }[range]
  return subMonths(new Date(), n)
}

// ── HTML generation ────────────────────────────────────────────────────────

function row(cells: string[], header = false): string {
  const tag = header ? 'th' : 'td'
  return `<tr>${cells.map(c => `<${tag}>${c}</${tag}>`).join('')}</tr>`
}

function table(headers: string[], rows: string[][]): string {
  if (!rows.length) return '<p style="color:#666;font-size:13px">No data in this range.</p>'
  return `<table>
    <thead>${row(headers, true)}</thead>
    <tbody>${rows.map(r => row(r)).join('')}</tbody>
  </table>`
}

function buildHtml(title: string, subtitle: string, sections: Array<{ title: string; html: string }>): string {
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width">
  <title>${title}</title>
  <style>
    * { box-sizing: border-box; }
    body {
      font-family: -apple-system, "Helvetica Neue", Arial, sans-serif;
      margin: 0; padding: 32px 40px; color: #000; font-size: 14px; line-height: 1.5;
    }
    @media print { body { padding: 16px 24px; } }
    header { border-bottom: 2px solid #000; padding-bottom: 14px; margin-bottom: 24px; }
    header h1 { margin: 0 0 4px; font-size: 22px; font-weight: 700; }
    header p  { margin: 0; color: #555; font-size: 12px; }
    .section  { margin-bottom: 32px; }
    .section h2 { font-size: 15px; font-weight: 700; text-transform: uppercase; letter-spacing: 0.05em; margin: 0 0 10px; color: #000; }
    table { width: 100%; border-collapse: collapse; font-size: 13px; margin-bottom: 4px; }
    th { background: #f2f2f2; text-align: left; padding: 6px 10px; border: 1px solid #ddd; font-weight: 600; font-size: 11px; text-transform: uppercase; letter-spacing: 0.04em; }
    td { padding: 6px 10px; border: 1px solid #ddd; }
    tr:nth-child(even) td { background: #fafafa; }
    .flag-high { color: #dc2626; font-weight: 600; }
    .flag-low  { color: #2563eb; font-weight: 600; }
    footer { margin-top: 40px; padding-top: 12px; border-top: 1px solid #ddd; color: #888; font-size: 11px; }
    @media print { .no-print { display: none !important; } }
  </style>
</head>
<body>
  <header>
    <h1>${title}</h1>
    <p>${subtitle}</p>
  </header>
  ${sections.map(s => `<div class="section"><h2>${s.title}</h2>${s.html}</div>`).join('')}
  <footer>
    Generated by Apollo Health · ${format(new Date(), 'MMMM d, yyyy')} ·
    This document is based on self-reported data and is for informational purposes only.
    Please discuss with your healthcare provider.
  </footer>
</body>
</html>`
}

// ── Section builders ──────────────────────────────────────────────────────

function buildInjectionsSection(
  injections: InjectionLog[],
  compounds: Compound[],
  compoundIds: number[],
  cutoff: Date | null,
): string {
  const compMap = new Map(compounds.map(c => [c.id!, c]))
  const filtered = injections
    .filter(i => compoundIds.includes(i.compoundId))
    .filter(i => !cutoff || parseISO(i.takenAt) >= cutoff)
    .slice(0, 500)

  return table(
    ['Date', 'Compound', 'Dose', 'Route', 'Site', 'Notes'],
    filtered.map(i => {
      const c = compMap.get(i.compoundId)
      return [
        format(parseISO(i.takenAt), 'dd/MM/yyyy HH:mm'),
        c?.name ?? '—',
        `${i.dose ?? '—'} ${i.unit}`,
        i.route ?? 'IM',
        i.site ?? '—',
        i.notes ?? '',
      ]
    }),
  )
}

function buildLabsSection(
  exams: LabExam[],
  results: EnrichedResult[],
  cutoff: Date | null,
): string {
  const filteredExams = exams
    .filter(e => !cutoff || parseISO(e.collectedAt) >= cutoff)
    .sort((a, b) => b.collectedAt.localeCompare(a.collectedAt))

  if (!filteredExams.length) return '<p style="color:#666;font-size:13px">No lab results in this range.</p>'

  const examIds = new Set(filteredExams.map(e => e.id))
  const filteredResults = results.filter(r => examIds.has(r.examId))

  // Group by marker for display
  const byMarker = new Map<string, Array<{ date: string; value: string; unit: string; exam: string }>>()
  for (const r of filteredResults) {
    const exam = filteredExams.find(e => e.id === r.examId)
    if (!exam) continue
    const key = r.marker
    if (!byMarker.has(key)) byMarker.set(key, [])
    byMarker.get(key)!.push({
      date: format(parseISO(exam.collectedAt), 'dd/MM/yyyy'),
      value: r.rawValue,
      unit: r.unit ?? '',
      exam: exam.name,
    })
  }

  // Build a flat table sorted by date
  const rows: string[][] = []
  for (const r of filteredResults) {
    const exam = filteredExams.find(e => e.id === r.examId)
    if (!exam) continue
    const status = (r.low !== undefined && r.value !== undefined && r.value < r.low) ? 'flag-low'
      : (r.high !== undefined && r.value !== undefined && r.value > r.high) ? 'flag-high'
      : ''
    rows.push([
      format(parseISO(exam.collectedAt), 'dd/MM/yyyy'),
      exam.name,
      r.marker,
      status ? `<span class="${status}">${r.rawValue}${r.unit ? ' ' + r.unit : ''}</span>` : `${r.rawValue}${r.unit ? ' ' + r.unit : ''}`,
      r.low !== undefined || r.high !== undefined ? `${r.low ?? ''}–${r.high ?? ''}` : '',
    ])
  }

  return table(['Date', 'Panel', 'Marker', 'Result', 'Reference'], rows)
}

function buildBPSection(vitals: VitalLog[], cutoff: Date | null): string {
  const filtered = vitals
    .filter(v => !cutoff || parseISO(v.measuredAt) >= cutoff)
    .slice(0, 200)
  return table(
    ['Date & Time', 'Systolic', 'Diastolic', 'Pulse', 'Notes'],
    filtered.map(v => [
      format(parseISO(v.measuredAt), 'dd/MM/yyyy HH:mm'),
      String(v.systolic),
      String(v.diastolic),
      v.pulse ? String(v.pulse) : '—',
      v.notes ?? '',
    ]),
  )
}

// ── Component ─────────────────────────────────────────────────────────────

export function ExportSheet({
  compounds,
  injections,
  vitals,
  exams,
  results,
  onClose,
}: {
  compounds: Compound[]
  injections: InjectionLog[]
  vitals: VitalLog[]
  exams: LabExam[]
  results: EnrichedResult[]
  onClose: () => void
}) {
  const [range, setRange] = useState<DateRange>('ALL')
  const [inclInjections, setInclInjections] = useState(true)
  const [inclLabs, setInclLabs] = useState(true)
  const [inclBP, setInclBP]   = useState(false)
  const [selectedCompounds, setSelectedCompounds] = useState<number[]>([])

  // Compounds with injection history — deduplicated by canonical name so
  // "Testosterone" and "Testosterone Enanthate" don't both appear as separate entries
  const compoundsWithHistory = useMemo(() => {
    const ids = new Set(injections.map(i => i.compoundId))
    const all = compounds.filter(c => ids.has(c.id!))
    // Keep only one compound per unique base name (prefer the one with most injections)
    const countById = new Map<number, number>()
    for (const inj of injections) countById.set(inj.compoundId, (countById.get(inj.compoundId) ?? 0) + 1)
    const seen = new Map<string, Compound>()
    for (const c of all) {
      // Canonical key: strip ester/form from name, lower-case first word
      const key = c.name.toLowerCase().split(/[\s-]/)[0]
      const existing = seen.get(key)
      if (!existing || (countById.get(c.id!) ?? 0) > (countById.get(existing.id!) ?? 0)) {
        seen.set(key, c)
      }
    }
    return [...seen.values()]
  }, [compounds, injections])

  // Init selected compounds on mount
  useMemo(() => {
    if (selectedCompounds.length === 0 && compoundsWithHistory.length > 0) {
      setSelectedCompounds(compoundsWithHistory.map(c => c.id!))
    }
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [compoundsWithHistory.length])

  function toggleCompound(id: number) {
    setSelectedCompounds(prev =>
      prev.includes(id) ? prev.filter(x => x !== id) : [...prev, id]
    )
  }

  function openExport() {
    const cutoff = cutoffFor(range)
    const sections: Array<{ title: string; html: string }> = []
    const titleParts: string[] = []

    if (inclInjections && selectedCompounds.length > 0) {
      const names = compounds
        .filter(c => selectedCompounds.includes(c.id!))
        .map(c => c.name)
        .join(', ')
      sections.push({
        title: `Injection history — ${names}`,
        html: buildInjectionsSection(injections, compounds, selectedCompounds, cutoff),
      })
      titleParts.push('Injections')
    }

    if (inclLabs && exams.length > 0) {
      sections.push({
        title: 'Lab results',
        html: buildLabsSection(exams, results, cutoff),
      })
      titleParts.push('Labs')
    }

    if (inclBP && vitals.length > 0) {
      sections.push({
        title: 'Blood pressure log',
        html: buildBPSection(vitals, cutoff),
      })
      titleParts.push('Blood pressure')
    }

    if (!sections.length) return

    const title = `Apollo Health — ${titleParts.join(' · ')}`
    const rangeLabel = RANGE_LABELS[range]
    const subtitle = `Period: ${rangeLabel} · Patient health record export`
    const html = buildHtml(title, subtitle, sections)

    const win = window.open('', '_blank')
    if (win) {
      win.document.write(html)
      win.document.close()
      // Auto-prompt print after a short delay
      setTimeout(() => win.print(), 600)
    }
  }

  return (
    <div
      className="sheet-overlay"
      onClick={e => { if (e.target === e.currentTarget) onClose() }}
    >
      <div className="sheet">
        <div className="sheet-handle" />
        <div className="sheet-header">
          <h3>Share with doctor</h3>
          <button type="button" className="icon-button" onClick={onClose}><X size={16} /></button>
        </div>

        <div className="sheet-body" style={{ display: 'flex', flexDirection: 'column', gap: 22 }}>

          {/* Date range */}
          <div>
            <p style={{ margin: '0 0 10px', fontSize: 13, fontWeight: 600, color: 'var(--ink-dim)' }}>Date range</p>
            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: 6 }}>
              {(Object.entries(RANGE_LABELS) as [DateRange, string][]).map(([k, label]) => (
                <button
                  key={k}
                  type="button"
                  onClick={() => setRange(k)}
                  style={{
                    padding: '9px 6px',
                    borderRadius: 10,
                    fontSize: 12,
                    fontWeight: 600,
                    background: range === k ? 'var(--accent-soft)' : 'var(--surface-2)',
                    color: range === k ? 'var(--accent)' : 'var(--ink-dim)',
                    border: range === k ? '1.5px solid var(--accent)' : '1.5px solid transparent',
                  }}
                >
                  {label}
                </button>
              ))}
            </div>
          </div>

          {/* What to include */}
          <div>
            <p style={{ margin: '0 0 10px', fontSize: 13, fontWeight: 600, color: 'var(--ink-dim)' }}>Include</p>
            <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
              {/* Injections toggle + compound filter */}
              <label style={{ display: 'flex', alignItems: 'center', gap: 12, padding: '12px 14px', background: 'var(--surface-2)', borderRadius: 12, cursor: 'pointer' }}>
                <input type="checkbox" checked={inclInjections} onChange={e => setInclInjections(e.target.checked)} style={{ width: 18, height: 18, accentColor: 'var(--accent)', flexShrink: 0 }} />
                <div style={{ flex: 1, minWidth: 0 }}>
                  <strong style={{ fontSize: 14 }}>Injection history</strong>
                  <span style={{ display: 'block', fontSize: 12, color: 'var(--ink-mute)', marginTop: 1 }}>All logged doses</span>
                </div>
              </label>

              {/* Compound filter (shown when injections is checked) */}
              {inclInjections && compoundsWithHistory.length > 0 && (
                <div style={{ paddingLeft: 16, display: 'flex', flexDirection: 'column', gap: 6 }}>
                  <span style={{ fontSize: 11, color: 'var(--ink-mute)', fontWeight: 600, textTransform: 'uppercase', letterSpacing: '0.04em' }}>Filter by compound</span>
                  <div style={{ display: 'flex', gap: 6, flexWrap: 'wrap' }}>
                    {compoundsWithHistory.map(c => (
                      <button
                        key={c.id}
                        type="button"
                        onClick={() => toggleCompound(c.id!)}
                        style={{
                          padding: '5px 12px',
                          borderRadius: 100,
                          fontSize: 12,
                          fontWeight: 600,
                          background: selectedCompounds.includes(c.id!) ? (c.color ?? 'var(--accent)') : 'var(--surface-3)',
                          color: selectedCompounds.includes(c.id!) ? '#fff' : 'var(--ink-dim)',
                          border: 'none',
                        }}
                      >
                        {c.name}{c.ester ? ` (${c.ester})` : ''}
                      </button>
                    ))}
                  </div>
                </div>
              )}

              <label style={{ display: 'flex', alignItems: 'center', gap: 12, padding: '12px 14px', background: 'var(--surface-2)', borderRadius: 12, cursor: 'pointer' }}>
                <input type="checkbox" checked={inclLabs} onChange={e => setInclLabs(e.target.checked)} style={{ width: 18, height: 18, accentColor: 'var(--accent)', flexShrink: 0 }} />
                <div>
                  <strong style={{ fontSize: 14 }}>Lab results</strong>
                  <span style={{ display: 'block', fontSize: 12, color: 'var(--ink-mute)', marginTop: 1 }}>{exams.length} panel{exams.length !== 1 ? 's' : ''} on file</span>
                </div>
              </label>

              <label style={{ display: 'flex', alignItems: 'center', gap: 12, padding: '12px 14px', background: 'var(--surface-2)', borderRadius: 12, cursor: 'pointer' }}>
                <input type="checkbox" checked={inclBP} onChange={e => setInclBP(e.target.checked)} style={{ width: 18, height: 18, accentColor: 'var(--accent)', flexShrink: 0 }} />
                <div>
                  <strong style={{ fontSize: 14 }}>Blood pressure log</strong>
                  <span style={{ display: 'block', fontSize: 12, color: 'var(--ink-mute)', marginTop: 1 }}>{vitals.length} reading{vitals.length !== 1 ? 's' : ''} on file</span>
                </div>
              </label>
            </div>
          </div>

          {/* Export button */}
          <button
            type="button"
            className="primary-button"
            style={{ width: '100%', justifyContent: 'center', height: 50, fontSize: 16 }}
            onClick={openExport}
            disabled={!inclInjections && !inclLabs && !inclBP}
          >
            <FileText size={17} /> Open for printing / PDF
          </button>

          <p style={{ margin: '0', fontSize: 11, color: 'var(--ink-mute)', textAlign: 'center', lineHeight: 1.5 }}>
            Opens a clean document in a new tab. Use your browser's <strong>Print → Save as PDF</strong> to save or share.
          </p>
        </div>
      </div>
    </div>
  )
}
